# Generated by Django 6.0.1 on 2026-07-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_comentariocontacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='updatep',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
